# Default values for netbird.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


global:
  namespace: 'netbird'
  # Domain name used for access, ex netbird.example.com
  domain:
    global: '' # This is the only required domain.  The below ones are optional for if your network topology requires them.
    vpn: ''  # This is the domain used internally by netbird for vpn clients.
  dashboard:
    port: 80
  server:
    port: 80
    stun_port: 3478
    encryption_key: '' # openssl rand -base64 32
    # Shared HMAC secret the relay uses to validate peer tokens.
    auth_secret: '' # openssl rand -base64 32

  persistence:
    enabled: true
    storageClass:
    volumeName: 'data'
    existingClaim: ''
    accessModes:
      - ReadWriteOnce
    size: 4Gi
    volumeMode:
    annotations: {}
    labels: {}
    selector: {}
    dataSource: {}
    overrideVolume:
    overrideVolumeMount:

  ingress:
    enabled: false
    className: ''
    annotations: {}
    extra_hosts: []

  route:
    enabled: false
    vendor: ''
    parentRefs: []
    # STUN likely uses a different port in the gateway, so you can specify a different parent ref here
    stunParentRefs: []
    annotations: {}

  serviceAccount:
    create: true
    automount: true
    annotations: { }
    name: ""


dashboard:
  image:
    repository: netbirdio/dashboard
    tag: v2.33.0
    pullPolicy: IfNotPresent
  annotations: {}
  labels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  replicaCount: 1
  resources: {}
  livenessProbe:
  readinessProbe:
  service:
    type: ClusterIP
    annotations: {}
  extra_volumes: []
  extra_volumeMounts: []


server:
  image:
    repository: netbirdio/netbird-server
    tag: 0.66.0
    pullPolicy: IfNotPresent
  annotations: {}
  labels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  replicaCount: 1
  resources: {}
  livenessProbe:
  readinessProbe:
  service:
    type: ClusterIP
    annotations: {}
  extra_volumes: []
  extra_volumeMounts: []
  extra_args: []
  persistence:
    dataDir: /var/lib/netbird
    mountPath: /var/lib/netbird
    configMountPath: /etc/netbird/config.yaml
    subPath: 'server'



