apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-server-http
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
    netbird-app: {{ include "netbird.fullname" . }}-server
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.global.server.port }}
  selector:
    {{- include "netbird.selectorLabels" . | nindent 4 }}
    netbird-app: {{ include "netbird.fullname" . }}-server
