{{- if .Values.global.route.enabled -}}
{{- $fullName := include "netbird.fullname" . -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-server
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
  {{- with .Values.global.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.global.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    - {{ default .Values.global.domain.global  | quote }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}-server
          port: {{ .Values.global.server.port }}
      matches:
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /oauth2
        - path:
            type: PathPrefix
            value: /ws-proxy
        - path:
            type: PathPrefix
            value: /relay
      timeouts:
        request: 3600s
        backendRequest: 3600s


---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-dashboard
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
  {{- with .Values.global.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.global.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    - {{ default .Values.global.domain.global  | quote }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}-dashboard
          port: {{ .Values.global.dashboard.port }}
      matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: 3600s
        backendRequest: 3600s



{{- with .Values.global.route.stunParentRefs }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: {{ $fullName }}-stun
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "netbird.labels" $ | nindent 4 }}
  {{- with $.Values.global.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml . | nindent 4 }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}-server
          port: {{ $.Values.global.server.stun_port }}
{{- end }}



---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ $fullName }}-server-management
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
  {{- with .Values.global.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.global.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    - {{ default .Values.global.domain.global  | quote }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}-server
          port: {{ .Values.global.server.port }}
      matches:
        - method:
            type: Exact
            service: management.ManagementService



---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ $fullName }}-server-signal
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
  {{- with .Values.global.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.global.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    - {{ default .Values.global.domain.global  | quote }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}-server
          port: {{ .Values.global.server.port }}
      matches:
        - method:
            type: Exact
            service: signalexchange.SignalExchange



{{ if eq .Values.global.route.vendor "envoy" -}}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ $fullName }}-server-management-timeouts
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  targetRefs:
    - group: 'gateway.networking.k8s.io'
      kind: GRPCRoute
      name: {{ $fullName }}-server-management
  timeout:
    http:
      requestTimeout: 0s
      connectionIdleTimeout: 86400s
  tcpKeepalive:
    idleTime: 30s
    interval: 30s
    probes: 5

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ $fullName }}-server-signal-timeouts
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  targetRefs:
    - group: 'gateway.networking.k8s.io'
      kind: GRPCRoute
      name: {{ $fullName }}-server-signal
  timeout:
    http:
      requestTimeout: 0s
      connectionIdleTimeout: 86400s
  tcpKeepalive:
    idleTime: 30s
    interval: 30s
    probes: 5
{{- end }}



{{- end }}
