apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
stringData:
  config.yaml: |
    server:
      listenAddress: ":{{ .Values.global.server.port }}"
      exposedAddress: "https://{{ .Values.global.domain.global }}:443"
{{- if .Values.global.server.stun.enabled }}
      stunPorts:
        - {{ include "netbird.stunPort" . }}
{{- end }}
{{- with .Values.global.server.stun.external }}
      stuns:
        {{- toYaml . | nindent 8 }}
{{- end }}
      metricsPort: 9090
      healthcheckAddress: ":9000"
      logLevel: "info"
      logFile: "console"
    
      authSecret: {{ required "global.server.auth_secret is required. Generate one with `openssl rand -base64 32`." .Values.global.server.auth_secret | quote }}
      dataDir: {{ .Values.server.persistence.dataDir }}
    
      auth:
        issuer: "https://{{ .Values.global.domain.global }}/oauth2"
        signKeyRefreshEnabled: true
        dashboardRedirectURIs:
          - "https://{{ .Values.global.domain.global }}/nb-auth"
          - "https://{{ .Values.global.domain.global }}/nb-silent-auth"
        cliRedirectURIs:
          - "http://localhost:53000/"
    
      reverseProxy:
        trustedHTTPProxies:
          - "0.0.0.0/0"

      store:
        engine: "sqlite"
        encryptionKey: {{ required "global.server.encryption_key is required. Generate one with `openssl rand -base64 32`." .Values.global.server.encryption_key | quote }}
